### ISSUE TITLE
Target standardization in tests

### ISSUE THREAD

**Issue by mcoumbes** [tenable/Tenable.io-SDK-for-Java#12]
Consistently use the scanTextTargets provided by the test block in build.gradle. I have found some locations that set other text targets and should use the provided targets.

ScanWorkflowsExamples sets scan targets using getTestDomain(). This should be set use getScanTextTargets() since these get ran as part of testing. There could be times where the user domain shouldn't be scanned, but the provided targets are expected to be.

There are also a few instances in ScansApiClientTest that "google.com" is used as the scan target. These scans aren't actually launched as part of the test, but we should use getScanTextTargets() instead.

**Comment by pierresc** [comment]
Done
