### ISSUE TITLE
Always clean up data generated by tests pass or fail

### ISSUE THREAD

**Issue by mcoumbes** [tenable/Tenable.io-SDK-for-Java#13]
There are many tests that if they fail do not properly clean up anything that was created as part of the test. Examples are tests for policies and agent groups. All tests should clean up after themselves regardless of pass or fail.

**Comment by pierresc** [comment]
We've done a pass on all unit tests and made sure to clean assets after the tests are run and before the tests executes so that it can clean up test assets from previous crash runs
