### ISSUE TITLE
Add support for changing the API endpoint

### ISSUE THREAD

**Issue by mcoumbes** [tenable/Tenable.io-SDK-for-Java#5]
Currently the endpoint is hard coded to "cloud.tenable.com". This is a good default but should be configurable like tenableIoAccessKey and tenableIoSecretKey. The Python SDK supports this through the endpoint option. See https://github.com/tenable/Tenable.io-SDK-for-Python/blob/master/tenable_io.ini.example

**Comment by pierresc** [comment]
Ok will add asap

**Comment by pierresc** [comment]
You can now overwrite the default endpoint either by using 2 new environment variables "TENABLE_IO_SCHEME" and "TENABLE_IO_HOST" or JVM properties "tenableIoScheme" and "tenableIoHost". Details in readme.md
