### ISSUE TITLE
ScanRef.getLastHistory returns oldest instead of newest history

### ISSUE THREAD

**Issue by JSurf** [tenable/Tenable.io-SDK-for-Java#50]
getLastHistory returns the oldest history entry instead of the most recent one

```
for (History h : scan.getHistory()) {
   System.out.println(h.getHistoryId()+" "+h.getUuid()+" "+h.getCreationDate());
}
```
Output:
12600153 ef4d2ae4-0e42-428c-8c71-a154b98a353b 1560439023
12599021 6a28abd1-8d28-4354-a443-03e29e34bb77 1560420000
12598777 db3c7d2a-6ce2-44c4-a1ff-9eb865f20ec5 1560415867
12595342 ac8afb8c-12ac-455d-901b-26a12dbc10cb 1560352747
12594672 809f3709-51ee-4280-b4f7-aa15a4a9a099 1560344887

```
System.out.println(scan.getLastHistory().getHistoryId());
```
Output:
12594672 809f3709-51ee-4280-b4f7-aa15a4a9a099 1560344887

Expected Output:
12600153 ef4d2ae4-0e42-428c-8c71-a154b98a353b 1560439023

**Comment by tenableAndrew** [comment]
This should be fixed in https://github.com/tenable/Tenable.io-SDK-for-Java/releases/tag/v1.3.3
