### ISSUE TITLE
ScanRef.download() returns empty document

### ISSUE THREAD

**Issue by JSurf** [tenable/Tenable.io-SDK-for-Java#51]
The code in download() does not set the expected chapters, so the download returns an empty document. Either set a default chapter or extend the download function to allow to pass chapters

```
	        ExportScanSettings settings = new ExportScanSettings();
	        settings.setFormat( format );
                // Missing code:
	        settings.setChapters("vuln_hosts_summary");

```

**Comment by tenableAndrew** [comment]
This should be fixed in https://github.com/tenable/Tenable.io-SDK-for-Java/releases/tag/v1.3.3
