### ISSUE TITLE
AgentsApi list() method return only first 50 record

### ISSUE THREAD

**Issue by sedrakpc** [tenable/Tenable.io-SDK-for-Java#59]
AgentsApi list() method return only first 50 record. Please provide some functionality to iterate over the all the agents.

```
NameValuePair limit = new BasicNameValuePair("limit", "500");
List<NameValuePair> params = new ArrayList<NameValuePair>();
params.add(limit);
client.getAgentsApi().list(params);
```
Not a good workaround. Thanks!

**Comment by tenableAndrew** [comment]
Unfortunately 50 is the default for the underlying [agent API](https://developer.tenable.com/reference#agents-list). We will stick with the default values unless additional params are provided.

This endpoint defaults to a limit of 50, but will accept `limit` values of 1-5000. The limit can also be used in conjunction with the `offset` param if there are more than 5000 agents to retrieve.
