### ISSUE TITLE
ServerApiClientTest.testServer failure

### ISSUE THREAD

**Issue by mcoumbes** [tenable/Tenable.io-SDK-for-Java#8]
Getting a failure for:
com.tenable.io.api.ServerApiClientTest > testServer FAILED
    java.lang.AssertionError at ServerApiClientTest.java:32

Test contains environment specific values that may vary for different environments.

**Comment by pierresc** [comment]
Hi Michael, 

 

 

Please pull the latest and give it another shot. I made sure to create a test user before creating the policies. I also relaxed a couple asserts in server tests.

 

 

Thank you,

pierre

**Comment by mcoumbes** [comment]
com.tenable.io.api.ServerApiClientTest.testServer passes for me as well now with the relaxed asserts.

Thank you!
