### ISSUE TITLE
PoliciesApiClientTest failures

### ISSUE THREAD

**Issue by mcoumbes** [tenable/Tenable.io-SDK-for-Java#9]
I am getting the following failures:
com.tenable.io.api.PoliciesApiClientTest > testCreateAndDelete FAILED
    com.tenable.io.core.exceptions.TenableIoException at PoliciesApiClientTest.java:34

com.tenable.io.api.PoliciesApiClientTest > testCreateAndCopyAndDelete FAILED
    com.tenable.io.core.exceptions.TenableIoException at PoliciesApiClientTest.java:45

com.tenable.io.api.PoliciesApiClientTest > testConfigure FAILED
    com.tenable.io.core.exceptions.TenableIoException at PoliciesApiClientTest.java:80

com.tenable.io.api.PoliciesApiClientTest > testDetails FAILED
    com.tenable.io.core.exceptions.TenableIoException at PoliciesApiClientTest.java:62

Failing with returned error of:
{"error":"User 'tioTestUsername0@domain' not found"}

These appear to be related to some issues with the permissions being created in CreateTestPolicy().
//permissions
        Permission permission = new Permission()
        .withId( 7 )
        .withName( getTestUsername( 0 ) )
        .withOwner( 1 )
        .withType( "user" )
        .withPermissions( 128 );

The Id and Owner are hard coded and would be environment specific. The username used may not exist (tioTestUsername0@domain). We should either make sure the test user is created and query it's Id to use for Id and Owner or possibly query what user we are running the tests as and use it's info for the permissions.

**Comment by pierresc** [comment]
Michael, did you try again since last Thursday? We are now creating test users prior to running those tests so I'm surprised this is still happening.

**Comment by mcoumbes** [comment]
These tests are still failing. The problem appears to be with the permissions code in CreateTestPolicy() that I commented on above. The Id and Owner are still hard coded. The Id needs to match the username being provided. The owner could also be that user's Id as well for the test.

**Comment by pierresc** [comment]
That should be addressed
